In [7]:
import pandas as pd
df1=pd.read_csv('input_data/agent_roster.csv')
df2=pd.read_csv('input_data/call_logs.csv')
df3=pd.read_csv('input_data/disposition_summary.csv')

In [14]:
df3

   agent_id org_id   call_date login_time
0      A001     O1  2025-04-28      11:58
1      A002     O1  2025-04-28      10:05
2      A003     O1  2025-04-28      10:24
3      A004     O3  2025-04-28       8:13
4      A005     O3  2025-04-28        NaN
5      A006     O1  2025-04-28      11:29
6      A007     O1  2025-04-28       8:36
7      A008     O1  2025-04-28       9:31
8      A009     O3  2025-04-28      11:46
9      A010     O3  2025-04-28      11:11
10     A011     O1  2025-04-28      11:08
11     A012     O3  2025-04-28        NaN
12     A013     O1  2025-04-28      10:01
13     A014     O3  2025-04-28      11:05
14     A015     O2  2025-04-28       8:05
15     A016     O1  2025-04-28       9:05
16     A017     O2  2025-04-28       8:57
17     A018     O1  2025-04-28        NaN
18     A019     O1  2025-04-28      11:43
19     A020     O2  2025-04-28       9:50

In [12]:
df2['call_date']=pd.to_datetime(df2['call_date'])
df2[df2['call_date']<pd.to_datetime('2025-04-28')]

Empty DataFrame
Columns: [call_id, agent_id, org_id, installment_id, status, duration, created_ts, call_date]
Index: []